name: CI

on:
  push:
    branches: [ main, 'revamp-**' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Test, Lint, Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e '.[dev]'

      - name: Install ruff & black
        run: |
          python -m pip install --upgrade ruff black

      - name: Lint with ruff
        run: |
          ruff check . || true

      - name: Format check with black
        run: |
          black --check .

      - name: Run tests
        run: |
          pytest -q

  # Optional deploy job placeholder (kept separate so CI remains valid).
  # Add a deployment job here if/when you need to publish pages or packages.
