name: Build, Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Test, Lint, Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e '.[dev]'

      - name: Install ruff & black
        run: |
          python -m pip install --upgrade ruff black

      - name: Lint with ruff
        run: |
          ruff check .

      - name: Format check with black
        run: |
          black --check .

      - name: Run tests
        run: |
          pytest -q
name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
      - "revamp-**"
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
name: Build, Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Test, Lint, Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e '.[dev]'

      - name: Install ruff & black
        run: |
          python -m pip install --upgrade ruff black

      - name: Lint with ruff
        run: |
          ruff check .

      - name: Format check with black
        run: |
          black --check .

      - name: Run tests
        run: |
          pytest -q
