name: CI — Python tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies (pytest)
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run pytest
        run: |
          python -m pytest -q
        continue-on-error: false

      - name: Fallback ingest check (runs when you don't want full pytest)
        if: always()
        run: |
          # If pytest failed, still run the lightweight ingest check for visibility
          python3 scripts/run_ingest_check.py || true
